"use strict";
/**
 * type4.js, the ANS-104 signature type 4 (Solana, Ed25519) corpus, generated by
 * @ardrive/turbo-sdk@2.1.0.
 *
 *   node type4.js           regenerate in memory and diff against type4-vectors.json
 *   node type4.js --write   regenerate and write type4-vectors.json
 *
 * Type 4 is deterministic: Ed25519 (RFC 8032) draws no randomness, so a seed
 * and an input fix every byte of the signed item, including the signature and
 * the id. That makes the corpus stronger than the type 1 one: it pins COMPLETE
 * signed items, and turbo-upload must reproduce each one byte for byte.
 *
 * The inputs are the 22 cases in cases.js. Each case gets its own key, its seed
 * derived in code from the case name, so no key material is committed:
 *
 *   seed = SHA-256(UTF-8("turbo-upload type 4 corpus/" + case.name))
 *
 * The public key is derived from the seed by tweetnacl (a turbo-sdk dependency),
 * not by turbo-upload, so the corpus does not lean on the code under test.
 *
 * test/type4.test.js reads type4-vectors.json and reproduces every item four
 * ways: the synchronous Node signer, signAsync with a keypair signer, signAsync
 * with a wallet-style signMessage signer, and the web build. The browser
 * harness does the same in Chromium, Firefox and WebKit.
 */
const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const { Buffer } = require("node:buffer");
const nacl = require("tweetnacl");
const cases = require("./cases.js");
const { encodeBase58 } = require("../src/base58.js");

const OUT = path.join(__dirname, "type4-vectors.json");
const SEED_PREFIX = "turbo-upload type 4 corpus/";
const SDK_VERSION = JSON.parse(
  fs.readFileSync(path.join(__dirname, "node_modules", "@ardrive", "turbo-sdk", "package.json"), "utf8"),
).version;

const sha256 = (b) => crypto.createHash("sha256").update(b).digest();

async function streamToBuffer(stream) {
  const parts = [];
  for await (const part of stream) parts.push(Buffer.from(part));
  return Buffer.concat(parts);
}

// turbo-sdk 2.1.0's CommonJS build cannot load on Node 18 (a transitive
// dependency is ESM only), so it is imported as ESM, which is also how the
// devnet probe loaded it.
let TurboFactory;

async function buildVector(c) {
  const seed = sha256(Buffer.from(SEED_PREFIX + c.name, "utf8"));
  const pair = nacl.sign.keyPair.fromSeed(new Uint8Array(seed));
  const secretKey = Buffer.from(pair.secretKey); // seed || public key, the Solana form
  const turbo = TurboFactory.authenticated({
    privateKey: encodeBase58(secretKey),
    token: "solana",
    // Never contacted: signing is local. Set so nothing defaults to production.
    paymentServiceConfig: { url: "http://127.0.0.1:9" },
    uploadServiceConfig: { url: "http://127.0.0.1:9" },
  });

  const dataItemOpts = {};
  if (c.tags.length) dataItemOpts.tags = c.tags;
  if (c.target) dataItemOpts.target = c.target;
  if (c.anchor) dataItemOpts.anchor = c.anchor;

  const data = Buffer.from(c.data);
  const { dataItemStreamFactory, dataItemSizeFactory } = await turbo.signer.signDataItem({
    fileStreamFactory: () => data,
    fileSizeFactory: () => data.length,
    dataItemOpts,
  });
  const signed = await streamToBuffer(dataItemStreamFactory());
  if (signed.length !== dataItemSizeFactory()) {
    throw new Error(`${c.name}: turbo-sdk reported ${dataItemSizeFactory()} bytes and produced ${signed.length}`);
  }
  const signature = signed.subarray(2, 66);
  return {
    name: c.name,
    description: c.description,
    seed_hex: seed.toString("hex"),
    public_key_base58: encodeBase58(Buffer.from(pair.publicKey)),
    input: {
      data_hex: data.toString("hex"),
      tags: c.tags,
      target_b64url: c.target ?? null,
      anchor_utf8: c.anchor ?? null,
    },
    expected: {
      signed_item_hex: signed.toString("hex"),
      signed_item_length: signed.length,
      signature_hex: signature.toString("hex"),
      id_b64url: sha256(signature).toString("base64url"),
    },
  };
}

async function generate() {
  ({ TurboFactory } = await import("@ardrive/turbo-sdk"));
  const vectors = [];
  for (const c of cases) vectors.push(await buildVector(c));
  return {
    format: "ans104-type4-conformance-vectors",
    version: 1,
    generated_by: `@ardrive/turbo-sdk@${SDK_VERSION}`,
    signature_type: {
      id: 4,
      name: "solana",
      algorithm: "Ed25519 (RFC 8032), deterministic",
      signature_length: 64,
      owner_length: 32,
      signed_message:
        "the 96 ASCII bytes of the lowercase hex of the 48-byte deep hash, NOT the deep hash itself",
    },
    seed_rule: `seed = SHA-256(UTF-8("${SEED_PREFIX}" + name)); public key from the seed by tweetnacl`,
    notes: [
      "Ed25519 is deterministic, so every byte under `expected`, signature and id included, must match exactly.",
      "No secret key is stored: each one is derived from its case name by the seed rule.",
    ],
    vectors,
  };
}

(async () => {
  const corpus = await generate();
  const text = JSON.stringify(corpus, null, 2) + "\n";
  if (process.argv.includes("--write")) {
    fs.writeFileSync(OUT, text);
    console.log(`wrote ${path.basename(OUT)}: ${corpus.vectors.length} vectors from ${corpus.generated_by}, ` +
      `${(Buffer.byteLength(text) / 1024).toFixed(1)} KiB`);
    return;
  }
  const committed = fs.readFileSync(OUT, "utf8");
  if (committed !== text) {
    const want = JSON.parse(committed).vectors;
    for (const v of corpus.vectors) {
      const w = want.find((x) => x.name === v.name);
      if (!w || JSON.stringify(w) !== JSON.stringify(v)) console.error(`  DIFFERS: ${v.name}`);
    }
    console.error(`type4-vectors.json does not match what ${corpus.generated_by} produces today.`);
    process.exit(1);
  }
  console.log(`type4-vectors.json matches ${corpus.generated_by}: ${corpus.vectors.length} vectors regenerated, byte-identical`);
})().catch((err) => {
  console.error(err);
  process.exit(1);
});
