"use strict";
/**
 * verify.js, the test.
 *
 *   A. reference-signer.js reproduces every deterministic value in vectors.json.
 *   B. cross-verification: an item signed by us verifies under arbundles, and an item
 *      signed by arbundles verifies under us. Byte-equal deep hashes are necessary but
 *      not sufficient, this is the check that actually matters.
 *
 *   node verify.js            all vectors
 *   node verify.js <name>...  only the named vectors
 */
const crypto = require("node:crypto");
const { Buffer } = require("node:buffer");
const ref = require("./reference-signer.js");
const arb = require("./arbundles.js");
const vectorsFile = require("./vectors.json");
const jwk = require("./test-key.json");

const sha256 = (b) => crypto.createHash("sha256").update(b).digest();
const hex = (b) => Buffer.from(b).toString("hex");
const arbSigner = new arb.ArweaveSigner(jwk);

const filter = process.argv.slice(2);
const vectors = filter.length ? vectorsFile.vectors.filter((v) => filter.includes(v.name)) : vectorsFile.vectors;

let pass = 0, fail = 0;
const failures = [];

function check(vecName, label, actual, expected) {
  const ok = actual === expected;
  if (ok) pass++;
  else {
    fail++;
    failures.push({ vecName, label, actual, expected });
  }
  return ok;
}

function shorten(s, n = 96) {
  s = String(s);
  return s.length > n ? s.slice(0, n) + `…(${s.length} chars)` : s;
}

function firstDiff(a, b) {
  const A = String(a), B = String(b);
  for (let i = 0; i < Math.max(A.length, B.length); i++) if (A[i] !== B[i]) return i;
  return -1;
}

(async () => {
  console.log(`ANS-104 conformance run`);
  console.log(`  corpus     : vectors.json v${vectorsFile.version}, generated by ${vectorsFile.generated_by} on ${vectorsFile.generated_with_node}`);
  console.log(`  node       : ${process.version}`);
  console.log(`  vectors    : ${vectors.length}${filter.length ? " (filtered)" : ""}`);
  console.log("");

  // ---------- global: PSS randomness ----------
  const probeMsg = Buffer.from("randomness probe");
  const r1 = ref.signMessage(jwk, probeMsg), r2 = ref.signMessage(jwk, probeMsg);
  const a1 = Buffer.from(await arbSigner.sign(probeMsg)), a2 = Buffer.from(await arbSigner.sign(probeMsg));
  console.log(`[global] RSA-PSS is randomised (signatures over identical input must differ)`);
  console.log(`         reference-signer: ${r1.equals(r2) ? "IDENTICAL  <-- unexpected" : "differ  OK"}`);
  console.log(`         arbundles       : ${a1.equals(a2) ? "IDENTICAL  <-- unexpected" : "differ  OK"}`);
  if (r1.equals(r2)) { fail++; failures.push({ vecName: "global", label: "ref PSS randomised", actual: "identical", expected: "differ" }); } else pass++;
  if (a1.equals(a2)) { fail++; failures.push({ vecName: "global", label: "arb PSS randomised", actual: "identical", expected: "differ" }); } else pass++;

  // ---------- global: salt length ----------
  const pub = ref.publicKeyFromOwner(ref.ownerFromJwk(jwk));
  const saltOf = (sig) => {
    const em = crypto.publicDecrypt({ key: pub, padding: crypto.constants.RSA_NO_PADDING }, sig);
    const hLen = 32, emLen = em.length, emBits = 4095;
    const H = em.subarray(emLen - hLen - 1, emLen - 1);
    const db = Buffer.from(em.subarray(0, emLen - hLen - 1));
    let mask = [];
    for (let c = 0, n = 0; n < db.length; c++) {
      const cb = Buffer.alloc(4); cb.writeUInt32BE(c);
      const h = crypto.createHash("sha256").update(H).update(cb).digest();
      mask.push(h); n += h.length;
    }
    mask = Buffer.concat(mask).subarray(0, db.length);
    for (let i = 0; i < db.length; i++) db[i] ^= mask[i];
    db[0] &= 0xff >> (8 * emLen - emBits);
    return db.length - db.indexOf(0x01) - 1;
  };
  const saltRef = saltOf(r1), saltArb = saltOf(a1);
  console.log(`[global] PSS salt length recovered from the encoded message`);
  console.log(`         arbundles       : ${saltArb} bytes`);
  console.log(`         reference-signer: ${saltRef} bytes`);
  console.log(`         expected (max)  : ${ref.maxSaltLength(4096, 32)} bytes`);
  check("global", "salt length arbundles", saltArb, 478);
  check("global", "salt length reference", saltRef, 478);
  console.log("");

  // ---------- per vector ----------
  const rows = [];
  for (const v of vectors) {
    const before = fail;
    const inp = v.input;
    const data = Buffer.from(inp.data_hex, "hex");
    const opts = {
      data,
      tags: inp.tags,
      target: inp.target_b64url ?? undefined,
      anchor: inp.anchor_utf8 ?? undefined,
      owner: ref.ownerFromJwk(jwk),
    };

    // --- A. deterministic reproduction ---
    let unsigned, parsed, dh;
    try {
      unsigned = ref.createDataItem(opts);
      parsed = ref.parseDataItem(unsigned);
      dh = ref.getSignatureData(unsigned);

      const tagBytes = inp.tags.length ? ref.serializeTags(inp.tags) : Buffer.alloc(0);
      check(v.name, "tag_bytes_hex", hex(tagBytes), v.expected.tag_bytes_hex);
      check(v.name, "tag_bytes_len", tagBytes.length, v.expected.tag_bytes_len);
      check(v.name, "raw_target_hex", hex(parsed.rawTarget), v.expected.raw_target_hex);
      check(v.name, "raw_anchor_hex", hex(parsed.rawAnchor), v.expected.raw_anchor_hex);
      check(v.name, "raw_data_hex", hex(parsed.rawData), v.expected.raw_data_hex);
      check(v.name, "tag_count", parsed.tagCount, v.expected.tag_count);

      const o = v.expected.offsets;
      check(v.name, "offset.owner", parsed.offsets.ownerStart, o.owner);
      check(v.name, "offset.target_presence_byte", parsed.offsets.targetStart, o.target_presence_byte);
      check(v.name, "offset.anchor_presence_byte", parsed.offsets.anchorStart, o.anchor_presence_byte);
      check(v.name, "offset.tags_start", parsed.offsets.tagsStart, o.tags_start);
      check(v.name, "offset.data_start", parsed.offsets.dataStart, o.data_start);
      check(v.name, "offset.total_length", parsed.offsets.totalLength, o.total_length);

      check(v.name, "unsigned_item_hex", hex(unsigned), v.expected.unsigned_item_hex);
      check(v.name, "unsigned_item_sha256", hex(sha256(unsigned)), v.expected.unsigned_item_sha256);
      const skel = Buffer.from(unsigned); skel.fill(0, 2, 2 + 512 + 512);
      check(v.name, "keyless_skeleton_sha256", hex(sha256(skel)), v.expected.keyless_skeleton_sha256);

      const chunks = [
        Buffer.from("dataitem", "utf8"), Buffer.from("1", "utf8"), Buffer.from("1", "utf8"),
        parsed.rawOwner, parsed.rawTarget, parsed.rawAnchor, parsed.rawTags, parsed.rawData,
      ].map(hex);
      check(v.name, "deep_hash_input_chunks_hex", JSON.stringify(chunks), JSON.stringify(v.expected.deep_hash_input_chunks_hex));
      check(v.name, "deep_hash_hex", hex(dh), v.expected.deep_hash_hex);
    } catch (e) {
      fail++; failures.push({ vecName: v.name, label: "reference-signer threw", actual: e.message, expected: "no throw" });
    }

    // --- B. cross-verification ---
    let oursUnderArb = "n/a", arbUnderOurs = "n/a", sampleUnderOurs = "n/a", sampleUnderArb = "n/a", idsAgree = "n/a";
    try {
      // ours -> arbundles
      const mine = ref.signDataItem(jwk, opts);
      oursUnderArb = await arb.DataItem.verify(Buffer.from(mine.binary));
      check(v.name, "our signed item verifies under arbundles", oursUnderArb, true);

      // arbundles -> ours
      const arbOpts = {};
      if (inp.tags.length) arbOpts.tags = inp.tags;
      if (inp.target_b64url) arbOpts.target = inp.target_b64url;
      if (inp.anchor_utf8) arbOpts.anchor = inp.anchor_utf8;
      const theirs = arb.createData(data, arbSigner, arbOpts);
      const theirId = await arb.sign(theirs, arbSigner);
      arbUnderOurs = ref.verifyDataItem(Buffer.from(theirs.getRaw()));
      check(v.name, "arbundles signed item verifies under ours", arbUnderOurs, true);

      // both id derivations agree on the same signature
      const theirBin = Buffer.from(theirs.getRaw());
      idsAgree = hex(ref.idFromSignature(ref.parseDataItem(theirBin).rawSignature)) === hex(theirId);
      check(v.name, "id = sha256(signature) agrees with arbundles", idsAgree, true);

      // the pinned sample signature must verify under both
      const spliced = Buffer.from(v.expected.unsigned_item_hex, "hex");
      spliced.set(Buffer.from(v.sample_signature.signature_hex, "hex"), 2);
      sampleUnderOurs = ref.verifyDataItem(spliced);
      sampleUnderArb = await arb.DataItem.verify(Buffer.from(spliced));
      check(v.name, "pinned sample signature verifies under ours", sampleUnderOurs, true);
      check(v.name, "pinned sample signature verifies under arbundles", sampleUnderArb, true);
      check(v.name, "pinned sample id = sha256(signature)",
        hex(sha256(Buffer.from(v.sample_signature.signature_hex, "hex"))), v.sample_signature.id_hex);
    } catch (e) {
      fail++; failures.push({ vecName: v.name, label: "cross-verification threw", actual: e.message, expected: "no throw" });
    }

    const ok = fail === before;
    rows.push({ name: v.name, ok, ours: oursUnderArb, theirs: arbUnderOurs, len: v.expected.offsets.total_length });
    console.log(`${ok ? "PASS" : "FAIL"}  ${v.name.padEnd(28)} ` +
      `item=${String(v.expected.offsets.total_length).padStart(5)}B  tags=${String(v.expected.tag_bytes_len).padStart(4)}B  ` +
      `ours->arb=${oursUnderArb}  arb->ours=${arbUnderOurs}`);
  }

  // ---------- limits ----------
  console.log("");
  console.log("[limits] inputs both implementations must reject");
  const owner = ref.ownerFromJwk(jwk);
  const limitProbes = [
    ["tag region over MAX_TAG_BYTES (4096)", () => ref.createDataItem({ data: "x", owner, tags: Array.from({ length: 200 }, (_, i) => ({ name: `long-tag-name-number-${i}`, value: `long-tag-value-number-${i}` })) })],
    ["target that is not 32 bytes", () => ref.createDataItem({ data: "x", owner, target: Buffer.from("short").toString("base64url") })],
    ["anchor that is not 32 bytes", () => ref.createDataItem({ data: "x", owner, anchor: "too-short" })],
    ["anchor supplied as 43-char base64url (a natural mistake)", () => ref.createDataItem({ data: "x", owner, anchor: Buffer.alloc(32).toString("base64url") })],
    ["non-string tag value", () => ref.createDataItem({ data: "x", owner, tags: [{ name: "n", value: 5 }] })],
  ];
  for (const [label, fn] of limitProbes) {
    const recorded = vectorsFile.limits.find((l) => l.case === label);
    let threw = false, msg = null;
    try { fn(); } catch (e) { threw = true; msg = e.message; }
    const ok = threw === recorded.throws;
    if (ok) pass++; else { fail++; failures.push({ vecName: "limits", label, actual: threw, expected: recorded.throws }); }
    console.log(`  ${ok ? "PASS" : "FAIL"}  ${label}`);
    console.log(`        arbundles: ${recorded.throws ? recorded.message : "accepted"}`);
    console.log(`        ours     : ${threw ? msg : "accepted"}`);
  }

  // ---------- tamper detection ----------
  console.log("");
  console.log("[negative] a mutated item must fail verification in both directions");
  {
    const v = vectors.find((x) => x.expected.tag_count > 0) ?? vectors[0];
    const inp = v.input;
    const mine = ref.signDataItem(jwk, {
      data: Buffer.from(inp.data_hex, "hex"), tags: inp.tags,
      target: inp.target_b64url ?? undefined, anchor: inp.anchor_utf8 ?? undefined,
      owner: ref.ownerFromJwk(jwk),
    });
    for (const [what, mutate] of [
      ["last data byte", (b) => { b[b.length - 1] ^= 0x01; }],
      ["a tag byte", (b) => { b[ref.parseDataItem(b).offsets.tagsStart + 17] ^= 0x01; }],
      ["a signature byte", (b) => { b[10] ^= 0x01; }],
    ]) {
      const bad = Buffer.from(mine.binary);
      mutate(bad);
      const ours = ref.verifyDataItem(bad);
      const theirs = await arb.DataItem.verify(Buffer.from(bad)).catch(() => "threw");
      const ok = ours === false && theirs === false;
      if (ok) pass++; else { fail++; failures.push({ vecName: "negative", label: `tamper ${what}`, actual: `ours=${ours} arb=${theirs}`, expected: "both false" }); }
      console.log(`  ${ok ? "PASS" : "FAIL"}  flip ${what.padEnd(18)} ours=${ours}  arbundles=${theirs}`);
    }
  }

  // ---------- the salt-length trap ----------
  // A signature made with the DIGEST salt length (32) instead of the maximum (478) is
  // non-conformant, but arbundles' verifier passes no explicit saltLength and Node's
  // verify default is RSA_PSS_SALTLEN_AUTO, so it accepts any salt length. Demonstrating
  // this is the point: cross-verification ALONE cannot catch a wrong salt length.
  console.log("");
  console.log("[salt trap] a 32-byte-salt (digest-length) signature is non-conformant but still verifies");
  {
    const v = vectors[0];
    const opts = {
      data: Buffer.from(v.input.data_hex, "hex"), tags: v.input.tags,
      target: v.input.target_b64url ?? undefined, anchor: v.input.anchor_utf8 ?? undefined,
      owner: ref.ownerFromJwk(jwk),
    };
    const unsigned = ref.createDataItem(opts);
    const msg = ref.getSignatureData(unsigned);
    const wrongSalt = ref.signMessage(jwk, msg, { saltLength: crypto.constants.RSA_PSS_SALTLEN_DIGEST });
    const item = Buffer.from(unsigned); item.set(wrongSalt, 2);
    const recovered = saltOf(wrongSalt);
    const underArb = await arb.DataItem.verify(Buffer.from(item));
    const underOursLoose = ref.verifyDataItem(item);
    const underOursStrict = ref.verifyDataItem(item, { strictSaltLength: true });
    console.log(`            recovered salt length      : ${recovered} bytes (conformant is 478)`);
    console.log(`            arbundles verifier         : ${underArb}   <-- accepts it`);
    console.log(`            our verifier, default      : ${underOursLoose}   <-- matches arbundles`);
    console.log(`            our verifier, strict salt  : ${underOursStrict}  <-- the only check that catches it`);
    check("salt-trap", "digest-salt signature has salt length 32", recovered, 32);
    check("salt-trap", "arbundles accepts a digest-salt signature", underArb, true);
    check("salt-trap", "our loose verifier matches arbundles", underOursLoose, true);
    check("salt-trap", "our strict verifier rejects it", underOursStrict, false);
  }

  // ---------- encoding divergence ----------
  // Informational, not an assertion: how many vectors would a naive implementation get
  // right if it just used its language's standard UTF-8 encoder for tag strings?
  console.log("");
  console.log("[encoding] strict standard-UTF-8 tag encoding vs arbundles' hand-rolled encoder");
  let strictOk = 0;
  const strictDiff = [];
  for (const v of vectors) {
    let got;
    try { got = hex(ref.serializeTags(v.input.tags, { stringEncoding: "utf8" })); }
    catch (e) { got = "THREW: " + e.message; }
    const matches = got === v.expected.tag_bytes_hex;
    if (matches) strictOk++;
    else strictDiff.push({ name: v.name, got, want: v.expected.tag_bytes_hex });
    // the corpus must have recorded this divergence honestly
    check(v.name, "encoding.strict_utf8_tag_bytes_match recorded correctly",
      matches, v.encoding.strict_utf8_tag_bytes_match);
    if (!matches) check(v.name, "encoding.strict_utf8_tag_bytes_hex recorded correctly",
      got, v.encoding.strict_utf8_tag_bytes_hex);
  }
  console.log(`         ${strictOk}/${vectors.length} vectors byte-identical under strict UTF-8`);
  for (const d of strictDiff) {
    console.log(`         DIFFERS: ${d.name}`);
    console.log(`           arbundles   : ${d.want}`);
    console.log(`           strict utf-8: ${d.got}`);
  }
  if (!strictDiff.length) console.log("         (no divergence observed, the WTF-8 path was not exercised)");

  // ---------- summary ----------
  console.log("");
  console.log("=".repeat(72));
  if (failures.length) {
    console.log(`FAILURES (${failures.length})`);
    for (const f of failures) {
      const d = firstDiff(f.expected, f.actual);
      console.log(`  ${f.vecName} :: ${f.label}`);
      console.log(`     expected: ${shorten(f.expected)}`);
      console.log(`     actual  : ${shorten(f.actual)}`);
      if (d >= 0 && String(f.expected).length > 96) console.log(`     first difference at character ${d}`);
    }
    console.log("");
  }
  console.log(`${fail === 0 ? "ALL GREEN" : "RED"}   assertions: ${pass} passed, ${fail} failed   vectors: ${rows.filter(r => r.ok).length}/${rows.length} clean`);
  console.log("=".repeat(72));
  process.exit(fail === 0 ? 0 : 1);
})();
