"use strict";
/**
 * The ANS-104 data-item format, without the cryptography: byte layout, tag
 * encoding and the deep-hash transcript. Synchronous, and Uint8Array only.
 *
 * Both builds run this file. The hash functions are INJECTED, never imported:
 * the Node build passes node:crypto, the web build passes the plain JavaScript
 * SHA-2 in ./sha2.js. Signing is not here at all; it belongs to whoever holds
 * the key.
 *
 * Byte layout, deep-hash transcript and tag encoding are pinned by
 * vectors/vectors.json, 22 conformance vectors generated from
 * @dha-team/arbundles@1.0.4, and conformance/type4-vectors.json, generated by
 * @ardrive/turbo-sdk@2.1.0. Where ANS-104 is silent, arbundles' behaviour is the
 * answer; those places are commented DE-FACTO below.
 *
 * Do not "clean up" anything marked DE-FACTO. Each one is a deliberate
 * bug-for-bug match, and each has a vector that fails if you remove it.
 */

const { TurboValidationError } = require("./errors.js");
const { toBytes, utf8Encode, utf8ByteLength, utf8Decode, concatBytes, fromBase64Url } = require("./bytes.js");

/** ANS-104 §2.2 signature registry, for the two types this package signs. */
const SIG_CONFIG = {
  1: { name: "arweave", sigLength: 512, ownerLength: 512, modulusBits: 4096 },
  // Type 4 signs the HEX STRING of the signature data, not the bytes. See
  // src/ed25519.js. Type 2 is the same widths without the hex step and is
  // deliberately not implemented: @ardrive/turbo-sdk emits type 4 for
  // token "solana", and two of our own libraries producing different ids for
  // the same key and content would be worse than supporting one fewer type.
  4: { name: "solana", sigLength: 64, ownerLength: 32 },
};
const SIG_TYPE_ARWEAVE = 1;
const SIG_TYPE_SOLANA = 4;

/** Cap on the serialized tag region, on BYTES, not tag count. Enforced on read and write. */
const MAX_TAG_BYTES = 4096;

/** arbundles refuses to parse anything shorter. */
const MIN_BINARY_SIZE = 80;

/** The smallest legal type 1 item: 2 + 512 + 512 + 1 + 1 + 16, no target/anchor/tags/data. */
const MIN_ITEM_SIZE = 1044;

/* ------------------------------------------------------------------ *
 * Little-endian unsigned integers                                     *
 * ------------------------------------------------------------------ */

function longToNByteArray(n, value) {
  if (value < 0) throw new TurboValidationError("unsigned only, cannot represent negative numbers");
  const out = new Uint8Array(n);
  let v = value;
  for (let i = 0; i < n; i++) {
    const byte = v & 0xff;
    out[i] = byte;
    v = (v - byte) / 256;
  }
  if (v !== 0) throw new TurboValidationError(`value ${value} does not fit in ${n} bytes`);
  return out;
}

function byteArrayToLong(bytes) {
  let value = 0;
  for (let i = bytes.length - 1; i >= 0; i--) value = value * 256 + bytes[i];
  return value;
}

/* ------------------------------------------------------------------ *
 * deepHash, Arweave's SHA-384 structured transcript hash             *
 * ------------------------------------------------------------------ */

/**
 * deepHash over a tree of byte strings.
 *
 *   blob b := SHA384( SHA384("blob" || decimal_ascii(len(b))) || SHA384(b) )
 *   list L := acc = SHA384("list" || decimal_ascii(len(L)))
 *             for each child c: acc = SHA384(acc || deepHash(c))
 *
 * The length is its DECIMAL ASCII representation, concatenated with no
 * separator, the tag for a 512-byte blob is the 7 bytes `blob512`.
 *
 * A child may also be `{ byteLength, sha384 }`: a blob whose bytes were hashed
 * elsewhere, as they streamed past. That is how an item too large to hold in
 * memory is signed; the result is identical to passing the bytes.
 *
 * @param {Uint8Array|string|Array|{byteLength:number, sha384:Uint8Array}} chunk
 * @param {{sha384: (b: Uint8Array) => Uint8Array}} hashes
 * @returns {Uint8Array} 48-byte SHA-384 digest
 */
function deepHash(chunk, hashes) {
  const { sha384 } = hashes;
  if (Array.isArray(chunk)) {
    let acc = sha384(utf8Encode(`list${chunk.length}`));
    for (const child of chunk) acc = sha384(concatBytes([acc, deepHash(child, hashes)]));
    return acc;
  }
  if (chunk && !(chunk instanceof Uint8Array) && typeof chunk === "object" && chunk.sha384 instanceof Uint8Array) {
    const tag = utf8Encode(`blob${chunk.byteLength}`);
    return sha384(concatBytes([sha384(tag), chunk.sha384]));
  }
  const data = toBytes(chunk);
  const tag = utf8Encode(`blob${data.byteLength}`);
  return sha384(concatBytes([sha384(tag), sha384(data)]));
}

/* ------------------------------------------------------------------ *
 * Tags, Avro binary encoding of array<record{name:string,value:string}> *
 * ------------------------------------------------------------------ */

/** Avro zigzag varint. 1 -> 0x02, 64 -> 0x80 0x01. */
function writeVarLong(out, n) {
  let m = n >= 0 ? n * 2 : -n * 2 - 1;
  for (;;) {
    const b = m & 0x7f;
    m = Math.floor(m / 128);
    if (m === 0) {
      out.push(b);
      return;
    }
    out.push(b | 0x80);
  }
}

function readVarLong(buf, state) {
  let n = 0;
  let k = 0;
  let b;
  do {
    b = buf[state.pos++];
    if (b === undefined) throw new TurboValidationError("varint ran off the end of the buffer");
    n += (b & 0x7f) * Math.pow(2, k);
    k += 7;
  } while (b & 0x80);
  return n % 2 ? -(n + 1) / 2 : n / 2;
}

/**
 * UTF-8 encode a tag string the way arbundles' AVSCTap.writeString does.
 *
 * DE-FACTO: arbundles has TWO encoders and they disagree on ill-formed input.
 *   byteLength <= 64 -> a hand-rolled loop that writes an UNPAIRED UTF-16
 *                       surrogate as its raw code point (WTF-8: U+D800 -> ED A0 80)
 *   byteLength  > 64 -> Buffer.prototype.write, i.e. standard UTF-8, which
 *                       substitutes U+FFFD (EF BF BD)
 *
 * For every well-formed string the two agree with each other and with standard
 * UTF-8, so this only matters for lone surrogates, which JS strings can hold
 * and most other languages' strings cannot. The declared length is the
 * standard UTF-8 length (3 either way), so the varint framing never desyncs:
 * the item stays structurally valid and verifiable, it gets a DIFFERENT ID
 * than a strict-UTF-8 implementation would produce for the same input.
 *
 * Vectors `lone-surrogate-tag-short` / `lone-surrogate-tag-long` pin both sides.
 * mode "utf8" forces standard UTF-8 and is only useful for comparing against
 * a strict implementation.
 */
function encodeStringBytes(s, mode) {
  const len = utf8ByteLength(s);
  if (mode === "utf8" || len > 64) return utf8Encode(s);
  const buf = new Uint8Array(len);
  let pos = 0;
  for (let i = 0; i < s.length; i++) {
    let c1 = s.charCodeAt(i);
    let c2;
    if (c1 < 0x80) {
      buf[pos++] = c1;
    } else if (c1 < 0x800) {
      buf[pos++] = (c1 >> 6) | 0xc0;
      buf[pos++] = (c1 & 0x3f) | 0x80;
    } else if ((c1 & 0xfc00) === 0xd800 && ((c2 = s.charCodeAt(i + 1)) & 0xfc00) === 0xdc00) {
      c1 = 0x10000 + ((c1 & 0x03ff) << 10) + (c2 & 0x03ff);
      i++;
      buf[pos++] = (c1 >> 18) | 0xf0;
      buf[pos++] = ((c1 >> 12) & 0x3f) | 0x80;
      buf[pos++] = ((c1 >> 6) & 0x3f) | 0x80;
      buf[pos++] = (c1 & 0x3f) | 0x80;
    } else {
      buf[pos++] = (c1 >> 12) | 0xe0;
      buf[pos++] = ((c1 >> 6) & 0x3f) | 0x80;
      buf[pos++] = (c1 & 0x3f) | 0x80;
    }
  }
  return buf.subarray(0, pos);
}

/**
 * Serialize tags to the ANS-104 tag region.
 *
 *   zigzag(count) || (varint(len(name)) name varint(len(value)) value)* || 0x00
 *
 * DE-FACTO: an EMPTY tag list serializes to ZERO bytes, not to a bare 0x00
 * terminator. Order is preserved and never sorted; duplicate names are legal;
 * empty names and empty values are legal.
 *
 * @param {Array<{name:string,value:string}>} tags
 * @param {{stringEncoding?: "arbundles"|"utf8"}} [opts]
 * @returns {Uint8Array}
 */
function serializeTags(tags, opts = {}) {
  const mode = opts.stringEncoding || "arbundles";
  if (!Array.isArray(tags)) throw new TurboValidationError("tags must be an array of {name, value}");
  if (tags.length === 0) return new Uint8Array(0);
  const out = [];
  writeVarLong(out, tags.length);
  for (const tag of tags) {
    if (typeof tag?.name !== "string" || typeof tag?.value !== "string") {
      throw new TurboValidationError(
        `Invalid tag format for ${JSON.stringify(tag)}, expected {name: string, value: string}`,
      );
    }
    for (const s of [tag.name, tag.value]) {
      const bytes = encodeStringBytes(s, mode);
      // The declared length is the UTF-8 BYTE length, not the character count
      // and not the UTF-16 code-unit count.
      writeVarLong(out, utf8ByteLength(s));
      for (const b of bytes) out.push(b);
    }
  }
  writeVarLong(out, 0); // terminating zero-length block
  const buf = Uint8Array.from(out);
  if (buf.length > MAX_TAG_BYTES) {
    throw new TurboValidationError(`Too many tag bytes (${buf.length} > ${MAX_TAG_BYTES})`);
  }
  return buf;
}

/** Parse a serialized tag region back into tags. */
function deserializeTags(buf) {
  const state = { pos: 0 };
  const tags = [];
  let n;
  while ((n = readVarLong(buf, state))) {
    if (n < 0) {
      // A negative count means a byte-size follows (Avro blocked-array form).
      n = -n;
      readVarLong(buf, state);
    }
    while (n--) {
      const readString = () => {
        const len = readVarLong(buf, state);
        // A negative length walks the cursor backwards, and the loop then
        // never ends: a malformed item hung verifyDataItem rather than failing.
        if (len < 0) throw new TurboValidationError("tag string has a negative length");
        if (state.pos + len > buf.length) {
          throw new TurboValidationError("tag string runs past the end of the buffer");
        }
        const s = buf.subarray(state.pos, state.pos + len);
        state.pos += len;
        return utf8Decode(s);
      };
      const name = readString();
      const value = readString();
      tags.push({ name, value });
    }
  }
  return tags;
}

/* ------------------------------------------------------------------ *
 * Item layout                                                         *
 * ------------------------------------------------------------------ */

/** A 32-byte field from bytes, or (for target) a base64url string. */
function targetBytes(target) {
  if (target == null) return null;
  if (typeof target === "string") {
    try {
      return fromBase64Url(target);
    } catch (cause) {
      throw new TurboValidationError(`Target is not valid base64url: ${cause.message}`, { cause });
    }
  }
  return toBytes(target);
}

/**
 * The header of a data item: every field before the data, signature zeroed.
 *
 * Split out so an item whose data is streamed can be built without holding the
 * data: the header is small, and the data follows it unchanged.
 */
function createDataItemHeader(opts) {
  const sigType = opts.signatureType ?? SIG_TYPE_ARWEAVE;
  const cfg = SIG_CONFIG[sigType];
  if (!cfg) throw new TurboValidationError(`unsupported signature type ${sigType} (only 1 / arweave is implemented)`);

  const owner = toBytes(opts.owner);
  if (owner.length !== cfg.ownerLength) {
    throw new TurboValidationError(`Owner must be ${cfg.ownerLength} bytes, but was incorrectly ${owner.length}`);
  }

  // DE-FACTO, and the trap everybody hits: `target` is base64url-decoded but
  // `anchor` is taken as RAW BYTES. Two adjacent 32-byte fields, two opposite
  // string conventions. A 43-char base64url anchor therefore throws.
  const target = targetBytes(opts.target);
  if (target && target.length !== 32) {
    throw new TurboValidationError(
      `Target must be 32 bytes but was incorrectly ${target.length}. ` +
        `A string target is base64url-decoded (43 characters).`,
    );
  }

  const anchor = opts.anchor == null ? null : toBytes(opts.anchor); // raw UTF-8 bytes, NOT base64url
  if (anchor && anchor.length !== 32) {
    throw new TurboValidationError(
      `Anchor must be 32 bytes, got ${anchor.length}. ` +
        `Unlike target, a string anchor is used as RAW BYTES, not base64url, ` +
        `pass 32 raw bytes or a 32-character string.`,
    );
  }

  const tags = opts.tags ?? [];
  const tagBytes = tags.length > 0 ? serializeTags(tags, opts) : new Uint8Array(0);

  const targetLength = 1 + (target ? target.length : 0);
  const anchorLength = 1 + (anchor ? anchor.length : 0);
  const tagsLength = 16 + tagBytes.length;

  const headerLength = 2 + cfg.sigLength + cfg.ownerLength + targetLength + anchorLength + tagsLength;
  const extra = opts.dataLength ?? 0;
  const bytes = new Uint8Array(headerLength + extra); // signature region stays zero

  bytes.set(longToNByteArray(2, sigType), 0);
  bytes.set(owner, 2 + cfg.sigLength);

  const targetStart = 2 + cfg.sigLength + cfg.ownerLength;
  bytes[targetStart] = target ? 1 : 0;
  if (target) bytes.set(target, targetStart + 1);

  const anchorStart = targetStart + targetLength;
  bytes[anchorStart] = anchor ? 1 : 0;
  if (anchor) bytes.set(anchor, anchorStart + 1);

  const tagsStart = anchorStart + anchorLength;
  bytes.set(longToNByteArray(8, tags.length), tagsStart);
  bytes.set(longToNByteArray(8, tagBytes.length), tagsStart + 8);
  if (tagBytes.length) bytes.set(tagBytes, tagsStart + 16);

  return { bytes, headerLength, sigType, owner, target, anchor, tagBytes };
}

/**
 * Build the unsigned data-item binary: all fields populated, signature zeroed.
 *
 * @param {object} opts
 * @param {Uint8Array|string} [opts.data]
 * @param {Array<{name:string,value:string}>} [opts.tags]
 * @param {string|Uint8Array} [opts.target] base64url string decoding to exactly 32 bytes
 * @param {string|Uint8Array} [opts.anchor] 32 RAW bytes, a string is its UTF-8 bytes, NOT base64url
 * @param {Uint8Array} opts.owner raw owner bytes, the width the signature type takes
 * @param {number} [opts.signatureType] 1 (default) or 4
 * @returns {Uint8Array}
 */
function createDataItem(opts) {
  const data = opts.data == null ? new Uint8Array(0) : toBytes(opts.data);
  const { bytes, headerLength } = createDataItemHeader({ ...opts, dataLength: data.length });
  bytes.set(data, headerLength);
  return bytes;
}

/**
 * The size in bytes of the signed item these options would produce, without
 * building it. Price this, not the payload length: the header alone is 1044
 * bytes for type 1 and 116 for type 4, before tags.
 */
function dataItemByteLength({ signatureType = SIG_TYPE_ARWEAVE, dataSize, tags = [], target, anchor }) {
  const cfg = SIG_CONFIG[signatureType];
  if (!cfg) throw new TurboValidationError(`unsupported signature type ${signatureType}`);
  if (!Number.isSafeInteger(dataSize) || dataSize < 0) {
    throw new TurboValidationError(`\`dataSize\` must be a non-negative integer, got ${JSON.stringify(dataSize)}.`);
  }
  const tagBytes = tags.length > 0 ? serializeTags(tags) : new Uint8Array(0);
  return (
    2 + cfg.sigLength + cfg.ownerLength +
    (target == null ? 1 : 33) +
    (anchor == null ? 1 : 33) +
    16 + tagBytes.length + dataSize
  );
}

/**
 * Resolve every field offset of a serialized item.
 *
 * Offsets past the owner are CHAINED, not fixed: walk the presence bytes.
 * DE-FACTO: a presence byte is tested `=== 1`; any other value means absent.
 *
 * Every raw field is a view into `binary`, not a copy.
 */
function parseDataItem(binary) {
  const buf = toBytes(binary);
  if (buf.length < MIN_BINARY_SIZE) throw new TurboValidationError("binary too short to be a data item");
  const sigType = byteArrayToLong(buf.subarray(0, 2));
  const cfg = SIG_CONFIG[sigType];
  if (!cfg) throw new TurboValidationError(`Unknown signature type: ${sigType}`);

  const sigStart = 2;
  const ownerStart = 2 + cfg.sigLength;
  const targetStart = ownerStart + cfg.ownerLength;
  const targetPresent = buf[targetStart] === 1;
  const anchorStart = targetStart + (targetPresent ? 33 : 1);
  const anchorPresent = buf[anchorStart] === 1;
  const tagsStart = anchorStart + (anchorPresent ? 33 : 1);
  const tagCount = byteArrayToLong(buf.subarray(tagsStart, tagsStart + 8));
  const tagBytesLen = byteArrayToLong(buf.subarray(tagsStart + 8, tagsStart + 16));
  const dataStart = tagsStart + 16 + tagBytesLen;

  return {
    signatureType: sigType,
    signatureLength: cfg.sigLength,
    ownerLength: cfg.ownerLength,
    offsets: { sigStart, ownerStart, targetStart, anchorStart, tagsStart, dataStart, totalLength: buf.length },
    rawSignature: buf.subarray(sigStart, sigStart + cfg.sigLength),
    rawOwner: buf.subarray(ownerStart, targetStart),
    rawTarget: targetPresent ? buf.subarray(targetStart + 1, targetStart + 33) : buf.subarray(0, 0),
    rawAnchor: anchorPresent ? buf.subarray(anchorStart + 1, anchorStart + 33) : buf.subarray(0, 0),
    tagCount,
    rawTags: buf.subarray(tagsStart + 16, tagsStart + 16 + tagBytesLen),
    rawData: buf.subarray(dataStart),
  };
}

/**
 * The deep-hash input list for an item's fields.
 *
 * DE-FACTO: absent target/anchor participate as ZERO-LENGTH blobs, they are not
 * skipped, the list is always 8 long. Element 2 is the ANS-104 format version
 * and element 3 is the signature type as DECIMAL ASCII; both are "1" for type 1
 * and they are different things.
 */
function signatureDataChunks({ signatureType, rawOwner, rawTarget, rawAnchor, rawTags, data }) {
  return [
    utf8Encode("dataitem"),
    utf8Encode("1"),
    utf8Encode(String(signatureType)),
    rawOwner,
    rawTarget,
    rawAnchor,
    rawTags,
    data,
  ];
}

/** The exact 48-byte message that gets signed, for a serialized item. */
function getSignatureData(binary, hashes) {
  const it = parseDataItem(binary);
  return deepHash(signatureDataChunks({ ...it, data: it.rawData }), hashes);
}

/**
 * Structural checks on a serialized item, before any signature check.
 *
 * Re-parsing the tag region and confirming the recovered count equals the
 * declared tag_count is not optional: without it, an item whose tag region
 * decodes to a different number of tags than it declares is accepted, and two
 * implementations disagree about what the item SAYS while both agree the
 * signature is valid.
 *
 * @returns {object|null} the parsed item, or null when it is malformed
 */
function parseAndCheckStructure(binary) {
  let it;
  try {
    it = parseDataItem(binary);
  } catch {
    return null;
  }
  if (it.rawTags.length > MAX_TAG_BYTES) return null;
  if (it.tagCount > 0) {
    try {
      if (deserializeTags(it.rawTags).length !== it.tagCount) return null;
    } catch {
      return null;
    }
  }
  return it;
}

module.exports = {
  SIG_CONFIG,
  SIG_TYPE_ARWEAVE,
  SIG_TYPE_SOLANA,
  MAX_TAG_BYTES,
  MIN_BINARY_SIZE,
  MIN_ITEM_SIZE,
  deepHash,
  serializeTags,
  deserializeTags,
  encodeStringBytes,
  longToNByteArray,
  byteArrayToLong,
  createDataItemHeader,
  createDataItem,
  dataItemByteLength,
  parseDataItem,
  signatureDataChunks,
  getSignatureData,
  parseAndCheckStructure,
};
